spring.application.name=Job Portal API

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging Configuration
logging.file.name=logs/jobportal.log
logging.file.path=logs

# JWT Configuration
app.jwt.secret=cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
app.jwt.expiration-ms=31104000000

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=429680244482-usqfi9bs1fepb2k5uln0f2qvl90tnp4m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google
